### ISSUE TITLE
Could not find FalconBMS installed - after install ver. 2.0.0

### ISSUE THREAD

**Issue by emcek** [chihirobelmo/FalconBMS-Alternative-Launcher#45]
I installed new version 2.0.0, it starts fine but by accidence I choose 4.32 (there was list in right low corner 4.35, 4.34 and 4.32).
And right now instead of main alternative launcher window:
![image](https://user-images.githubusercontent.com/475312/141660381-c4bf9aa4-ac8a-4077-b031-5d2838bf8f5d.png)
and then
![image](https://user-images.githubusercontent.com/475312/141660386-f7cf9a8e-2475-4792-bfec-e3a2a7331da2.png)
![image](https://user-images.githubusercontent.com/475312/141660391-04944ed2-4410-40ee-87a6-e0188b6bda25.png)

I can not find any config file for new launcher to select correct version of BMS

**Comment by emcek** [comment]
and what is really strange i stack trace I see: **C:\Users\chihi\....** which isn't my user name (probably some hardcode value.....)

**Comment by chihirobelmo** [comment]
Hi,
You can remove
 C:\Users\<users>\AppData\Local\Benchmark_Sims
 To reset settings for 2.0.0
 
 Showing 4.32 name is fixed in the latest commit.
 
 I believe "C:\Users\chihi" is just a matter of pdb file. It's not hardcoded in AL code I'm sure.

**Comment by emcek** [comment]
yes, helped ;)

**Comment by Hawkeye4040** [comment]
Did you for real just dump that into a Message Box? I would like to go on the record saying that is not why I added diagnostics logging and there is the file output method for this. This allows users to send their logs instead of screenshots. This is not at all how the diagnostics logging feature was intended to be used. Unfortunately, GitHub doesn't have a facepalm to put here.

**Comment by Hawkeye4040** [comment]
I'm not going to keep helping if you keep crapping all over the code I write. I put in hours on that and you just wrecked it for the third time now.

**Comment by chihirobelmo** [comment]
@Hawkeye4040 
Hi, sorry I didn't know you were working on the AL code I changed these days.
I just opened the Discussion and Project page on the AL GitHub so we can share what we are working on with AL right now. To prevent changing the same code at the same time.

**Comment by Hawkeye4040** [comment]
That's a good idea actually but I don't think that was the problem here. I was working on something and it's changing on me and I'm like stop stop stop pulling my hair out over here! AL setting should help but we might need something else here as well. 

Right now the best we have is either me annoying the hell out of you on discord just to write a line without stepping on yours or this. I think both are incredibly frustrating approaches but to be fair I don't have something better either to solve this one.

I guess keep going and I'll adjust it when you're done 🤕 this is going to really delay it though.

**Comment by emcek** [comment]
original issue solved so I will close
