### ISSUE TITLE
1.30 - TQS RDR Keybinds not working

### ISSUE THREAD

**Issue by rurounijones** [chihirobelmo/FalconBMS-Alternative-Launcher#8]
Thank you for releasing 1.30. I would not be playing BMS if not for this tool existing!

I am Attempting to bind the keybinds for TQS RDR CURSOR U/D/L/R is failng for me on the Thrustmaster Warthog throttle.

I am binding these controls to the hat next to the much maligned warthog throttle's "Nipple" (To which I have bound the associated Cursor X/Y axis, the idea being that I can use the hat for fine tuning).

The inputs are registering in The Alternate Launcher in that after setting them they will go to that entry if I activate the button. However in the Alternate launcher there is no associated numeric DX entry in the input column after they are bound (Attached GIF showing this) and the keybinds are not working inside Falcon BMS itself. 

![falconBMSAltLauncherTQSRDR](https://user-images.githubusercontent.com/21911/57056594-6c7a3a80-6cde-11e9-91d0-ee049e0aa63c.gif)

**Comment by chihirobelmo** [comment]
This is because of BMS only allows POV switches of a device which there X/Y axis are bound to Roll/Pitch. Currently, alt launcher is hiding those POV switches assignment which will not work in BMS. I think I can add such a description to a later version when you assigned POV switch at KeyMapping page. Anyway, until BMS supports multiple devices POV switches, alt launcher cannot solve this.

**Comment by rurounijones** [comment]
What a wierd limitation. So just to confirm, I cannot use this HAT for _anything_ in BMS. Thank you for the information.

I am not sure if you want this ticket closed now or leave it open until you add a description / message.

**Comment by chihirobelmo** [comment]
As a workaround, you can use TARGET to assign DX or keyboard emulation for throttle POV. 
Thank you and I will close this issue.
